const OPERATOR_RATE=0.2,WORKER_RATE=0.09,OPERATORS_KEY="production-operators-v2",WORKERS_KEY="production-workers-v1",RECORDS_KEY="production-records-v2";
const ADDITIONS={sarwa:{name:"سروة",price:5},sahra:{name:"سهرة",price:5},holiday:{name:"عطلة",price:10},dinner:{name:"العشاء",price:3}};
const seedOperators=[
 {id:"op1",name:"أحمد محمود",workers:[{id:"w1",name:"خالد سمير"},{id:"w2",name:"يوسف علي"},{id:"w3",name:"سامر عادل"}]},
 {id:"op2",name:"محمود حسن",workers:[{id:"w4",name:"وليد عمر"},{id:"w5",name:"رامي سالم"},{id:"w6",name:"حسام ناصر"}]},
 {id:"op3",name:"عمر سليمان",workers:[{id:"w7",name:"فادي إبراهيم"},{id:"w8",name:"أنس طارق"},{id:"w9",name:"زياد جمال"}]}
];
const seedRecords=[
 {id:"r1",date:"2026-09-02",operatorId:"op1",worker1Id:"w1",worker2Id:"w2",meters:125,additions:["sahra","dinner"]},{id:"r2",date:"2026-09-07",operatorId:"op1",worker1Id:"w2",worker2Id:"w3",meters:140,additions:["holiday"]},{id:"r3",date:"2026-09-13",operatorId:"op1",worker1Id:"w1",worker2Id:"",meters:108,additions:[]},
 {id:"r4",date:"2026-09-04",operatorId:"op2",worker1Id:"w4",worker2Id:"",meters:98},{id:"r5",date:"2026-09-12",operatorId:"op2",worker1Id:"w5",worker2Id:"w6",meters:132},{id:"r6",date:"2026-09-09",operatorId:"op3",worker1Id:"w7",worker2Id:"w8",meters:116}
];
const $=s=>document.querySelector(s);
const read=(key,fallback)=>{try{const value=JSON.parse(localStorage.getItem(key));return Array.isArray(value)?value:fallback}catch{return fallback}};
const initialOperators=read(OPERATORS_KEY,seedOperators);
const migratedWorkers=[...new Map(initialOperators.flatMap(operator=>operator.workers||[]).map(worker=>[worker.id,worker])).values()];
const defaultWorkers=migratedWorkers.length?migratedWorkers:[...new Map(seedOperators.flatMap(operator=>operator.workers).map(worker=>[worker.id,worker])).values()];
const state={operators:initialOperators.map(({id,name})=>({id,name})),workers:read(WORKERS_KEY,defaultWorkers),records:read(RECORDS_KEY,seedRecords),activeOperatorId:localStorage.getItem("active-operator-id")||"op1",activeWorkerId:null,editingRecordId:null,deleteAction:null};
const el={operator:$("#activeOperator"),month:$("#monthFilter"),date:$("#workDate"),worker1:$("#worker1Select"),worker2:$("#worker2Select"),meters:$("#metersInput"),form:$("#workForm"),recordsBody:$("#recordsBody"),payoutBody:$("#payoutBody")};
const money=n=>`${(Math.round((Number(n)+Number.EPSILON)*100)/100).toFixed(2)} د.أ`,number=n=>new Intl.NumberFormat("ar-JO",{maximumFractionDigits:2}).format(n),initials=name=>name.split(/\s+/).map(x=>x[0]).slice(0,2).join("");
const selectedAdditions=()=>[...document.querySelectorAll('input[name="additions"]:checked')].map(input=>input.value);
const additionsValue=keys=>(keys||[]).reduce((sum,key)=>sum+(ADDITIONS[key]?.price||0),0);
const additionsCell=keys=>keys?.length?`<div class="additions-list">${keys.map(key=>ADDITIONS[key]?`<span>${ADDITIONS[key].name} <b>${ADDITIONS[key].price}</b></span>`:"").join("")}</div>`:'<span class="muted">—</span>';
const currentOperator=()=>state.operators.find(o=>o.id===state.activeOperatorId)||state.operators[0];
const operatorById=id=>state.operators.find(operator=>operator.id===id);
const worker=id=>state.workers.find(w=>w.id===id);
function payPeriod(monthValue){const[year,month]=monthValue.split("-").map(Number),startMonth=month===1?12:month-1,startYear=month===1?year-1:year,pad=value=>String(value).padStart(2,"0"),start=`${startYear}-${pad(startMonth)}-21`,end=`${year}-${pad(month)}-20`;return{start,end,label:`${start.split("-").reverse().join("/")} — ${end.split("-").reverse().join("/")}`}}
const monthRecords=()=>{const period=payPeriod(el.month.value);return state.records.filter(r=>r.operatorId===state.activeOperatorId&&r.date>=period.start&&r.date<=period.end).sort((a,b)=>a.date.localeCompare(b.date))};

function persist(){localStorage.setItem(OPERATORS_KEY,JSON.stringify(state.operators));localStorage.setItem(WORKERS_KEY,JSON.stringify(state.workers));localStorage.setItem(RECORDS_KEY,JSON.stringify(state.records));localStorage.setItem("active-operator-id",state.activeOperatorId);$("#lastSaved").textContent=new Intl.DateTimeFormat("ar-JO",{hour:"numeric",minute:"2-digit"}).format(new Date())}
function fillOperatorSelect(){if(!state.operators.some(o=>o.id===state.activeOperatorId))state.activeOperatorId=state.operators[0]?.id||"";el.operator.innerHTML=state.operators.map(o=>`<option value="${o.id}">${o.name}</option>`).join("");el.operator.value=state.activeOperatorId}
function fillWorkers(selected1="",selected2=""){const workers=state.workers.filter(w=>!w.archived||w.id===selected1||w.id===selected2);el.worker1.innerHTML='<option value="">اختر العامل الأول</option>'+workers.map(w=>`<option value="${w.id}">${w.name}${w.archived?' (سابق)':''}</option>`).join("");el.worker2.innerHTML='<option value="">لا يوجد عامل ثانٍ</option>'+workers.map(w=>`<option value="${w.id}">${w.name}${w.archived?' (سابق)':''}</option>`).join("");el.worker1.value=workers.some(w=>w.id===selected1)?selected1:"";el.worker2.value=workers.some(w=>w.id===selected2)?selected2:"";syncWorkerChoices()}
function syncWorkerChoices(){[...el.worker1.options].forEach(o=>o.disabled=!!o.value&&o.value===el.worker2.value);[...el.worker2.options].forEach(o=>o.disabled=!!o.value&&o.value===el.worker1.value)}
function dateInfo(value){const d=new Date(`${value}T12:00:00`);return{day:new Intl.DateTimeFormat("ar-JO",{weekday:"long"}).format(d),month:new Intl.DateTimeFormat("ar-JO",{month:"short"}).format(d),num:number(d.getDate())}}
function renderHeader(){const op=currentOperator();if(!op)return;const[year,month]=el.month.value.split("-").map(Number),monthName=new Intl.DateTimeFormat("ar-JO",{month:"long",year:"numeric"}).format(new Date(year,month-1)),period=payPeriod(el.month.value);$("#operatorName").textContent=op.name;$("#operatorAvatar").textContent=initials(op.name);$("#workerCount").textContent=`${number(state.workers.filter(w=>!w.archived).length)} عمال متاحين`;$("#monthName").textContent=monthName;$("#periodRange").textContent=period.label;$("#sheetNumber").textContent=`رقم الكشف: WR-${year}${String(month).padStart(2,"0")}-${op.id.replace(/\D/g,"")||"1"}`;document.title=`كشف ${op.name} — ${monthName}`}
function personCell(person){return person?`<div class="person"><span class="person-avatar">${initials(person.name)}</span><span><strong>${person.name}</strong><small>عامل</small></span></div>`:'<span class="muted">عامل محذوف</span>'}
function renderRecords(){const rows=monthRecords(),op=currentOperator();el.recordsBody.innerHTML=rows.map((r,index)=>{const w1=worker(r.worker1Id),w2=worker(r.worker2Id),d=dateInfo(r.date),workerCount=w2?2:1,workerMeters=r.meters/workerCount;return`<tr><td><strong>${number(index+1)}</strong></td><td><strong>${d.day}</strong></td><td>${r.date.split("-").reverse().join("/")}</td><td>${personCell(w1)}</td><td>${w2?personCell(w2):'<span class="muted">—</span>'}</td><td>${additionsCell(r.additions)}</td><td><strong>${number(r.meters)}</strong> متر</td><td><strong>${number(workerMeters)}</strong> متر</td><td class="no-print"><div class="row-actions"><button class="icon-btn edit-record" data-id="${r.id}" aria-label="تعديل"><svg><use href="#i-edit"/></svg></button><button class="icon-btn delete delete-record" data-id="${r.id}" aria-label="حذف"><svg><use href="#i-trash"/></svg></button></div></td></tr>`}).join("");$("#emptyState").classList.toggle("hidden",rows.length>0);el.recordsBody.closest("table").classList.toggle("hidden",rows.length===0);$("#recordsSubtitle").textContent=`${number(rows.length)} سجلات للمشغل ${op.name}`;document.querySelectorAll(".edit-record").forEach(b=>b.onclick=()=>editRecord(b.dataset.id));document.querySelectorAll(".delete-record").forEach(b=>b.onclick=()=>askDeleteRecord(b.dataset.id))}
function renderTotals(){const rows=monthRecords(),op=currentOperator(),people=new Map();const add=(id,name,role,meters,date,rate)=>{if(!people.has(id))people.set(id,{name,role,meters:0,days:new Set(),rate});const p=people.get(id);p.meters+=meters;p.days.add(date)};rows.forEach(r=>{add(op.id,op.name,"مشغل",r.meters,r.date,OPERATOR_RATE);const w1=worker(r.worker1Id),w2=worker(r.worker2Id),workerMeters=r.meters/(w2?2:1);if(w1)add(w1.id,w1.name,"عامل",workerMeters,r.date,WORKER_RATE);if(w2)add(w2.id,w2.name,"عامل",workerMeters,r.date,WORKER_RATE)});const list=[...people.values()];el.payoutBody.innerHTML=list.map(p=>`<tr><td><div class="person"><span class="person-avatar">${initials(p.name)}</span><strong>${p.name}</strong></div></td><td><span class="role ${p.role==='عامل'?'worker':''}">${p.role}</span></td><td>${number(p.days.size)} أيام</td><td>${number(p.meters)} متر</td><td>${money(p.rate)}</td><td class="money">${money(p.meters*p.rate)}</td></tr>`).join("");const meters=rows.reduce((s,r)=>s+r.meters,0),additionsTotal=rows.reduce((s,r)=>s+additionsValue(r.additions),0),total=list.reduce((s,p)=>s+p.meters*p.rate,0);$("#totalMeters").textContent=`${number(meters)} متر`;$("#workDays").textContent=`${number(new Set(rows.map(r=>r.date)).size)} أيام`;$("#totalPayroll").textContent=money(total);$("#grandTotal").textContent=money(total);$("#recordsAdditionsTotal").textContent=money(additionsTotal);$("#recordsMetersTotal").textContent=`${number(meters)} متر`}
function renderPrintLedger(){const rows=monthRecords(),op=currentOperator(),minimumRows=14;$("#printOperatorName").textContent=op.name;$("#printMonthName").innerHTML=`${$("#monthName").textContent} · <bdi dir="ltr">${payPeriod(el.month.value).label}</bdi>`;$("#printSheetNumber").textContent=$("#sheetNumber").textContent.replace("رقم الكشف: ","");const filled=rows.map((r,index)=>{const w1=worker(r.worker1Id),w2=worker(r.worker2Id),d=dateInfo(r.date),workerCount=w2?2:1,workerMeters=r.meters/workerCount;return`<tr><td>${number(index+1)}</td><td>${d.day}</td><td>${r.date.split("-").reverse().join("/")}</td><td>${op.name}</td><td>${w1?.name||"—"}</td><td>${w2?.name||"—"}</td><td>${additionsCell(r.additions)}</td><td>${number(r.meters)}</td><td>${number(workerMeters)}</td><td>${money(r.meters*OPERATOR_RATE)}</td><td>${money(r.meters*WORKER_RATE)}</td></tr>`}).join("");const blanks=Array.from({length:Math.max(0,minimumRows-rows.length)},(_,index)=>`<tr class="blank-row"><td>${number(rows.length+index+1)}</td><td></td><td></td><td>${op.name}</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>`).join("");$("#printRecordsBody").innerHTML=filled+blanks;const meters=rows.reduce((sum,r)=>sum+r.meters,0),additionsTotal=rows.reduce((sum,r)=>sum+additionsValue(r.additions),0),operatorDue=meters*OPERATOR_RATE,workersDue=meters*WORKER_RATE;$("#printAdditionsTotal").textContent=money(additionsTotal);$("#printTotalMeters").textContent=number(meters);$("#printOperatorDue").textContent=money(operatorDue);$("#printWorkersDue").textContent=money(workersDue)}
function render(){fillOperatorSelect();fillWorkers();renderHeader();renderRecords();renderTotals();renderPrintLedger();renderWorkers();renderWorkerDetail();updatePreview()}
function updateAdditionsLabel(){const keys=selectedAdditions(),value=additionsValue(keys);$("#additionsLabel").textContent=keys.length?`${number(keys.length)} إضافات · ${money(value)}`:"بدون إضافات";$("#additionsToggle").classList.toggle("has-value",keys.length>0)}
function updatePreview(){const meters=Number(el.meters.value)||0,count=(el.worker1.value?1:0)+(el.worker2.value?1:0),workerMeters=count?meters/count:0,additionsTotal=additionsValue(selectedAdditions());$("#operatorPreview").textContent=money(meters*OPERATOR_RATE);$("#workersPreview").textContent=money(workerMeters*WORKER_RATE*count);$("#additionsPreview").textContent=money(additionsTotal);$("#workerPreviewLabel").childNodes[0].textContent=count===2?`العاملان (${number(workerMeters)} متر لكل عامل): `:`العامل (${number(workerMeters)} متر): `}
function resetForm(){state.editingRecordId=null;el.form.reset();const period=payPeriod(el.month.value),today=new Date(),todayValue=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}-${String(today.getDate()).padStart(2,"0")}`;el.date.min=period.start;el.date.max=period.end;el.date.value=todayValue<period.start?period.start:todayValue>period.end?period.end:todayValue;fillWorkers();clearErrors();updateAdditionsLabel();updatePreview();$("#formTitle").textContent="إضافة سجل عمل";$("#submitLabel").textContent="إضافة السجل";$("#cancelEdit").classList.add("hidden")}
function clearErrors(){document.querySelectorAll(".field.invalid").forEach(x=>x.classList.remove("invalid"))}
function validateRecord(){clearErrors();const bad=[],mark=(node,msg)=>{node.closest(".field").classList.add("invalid");$(`[data-error="${node.id}"]`).textContent=msg;bad.push(node)},period=payPeriod(el.month.value);if(!el.date.value)mark(el.date,"اختر التاريخ");if(el.date.value&&(el.date.value<period.start||el.date.value>period.end))mark(el.date,`التاريخ يجب أن يكون بين ${period.label}`);if(!el.worker1.value)mark(el.worker1,"اختر العامل الأول");if(el.worker1.value===el.worker2.value&&el.worker2.value)mark(el.worker2,"اختر عاملاً مختلفاً");if(!(Number(el.meters.value)>0))mark(el.meters,"أدخل عدداً صحيحاً");bad[0]?.focus();return!bad.length}
function submitRecord(e){e.preventDefault();if(!validateRecord())return;const item={id:state.editingRecordId||`r${Date.now()}`,date:el.date.value,operatorId:state.activeOperatorId,worker1Id:el.worker1.value,worker2Id:el.worker2.value,meters:Number(el.meters.value)};if(state.editingRecordId){state.records=state.records.map(r=>r.id===item.id?item:r);showToast("تم تعديل السجل","تم تحديث مستحقات الكشف.")}else{state.records.push(item);showToast("تمت إضافة السجل","تم حفظ العمل في كشف المشغل.")}persist();resetForm();render()}
function editRecord(id){const r=state.records.find(x=>x.id===id);if(!r)return;state.editingRecordId=id;el.date.value=r.date;fillWorkers(r.worker1Id,r.worker2Id);el.meters.value=r.meters;updatePreview();$("#formTitle").textContent="تعديل سجل العمل";$("#submitLabel").textContent="حفظ التعديل";$("#cancelEdit").classList.remove("hidden");$(".entry-card").scrollIntoView({behavior:"smooth",block:"center"})}
function openOperatorDialog(edit=false){const op=edit?currentOperator():null;$("#operatorEditId").value=op?.id||"";$("#operatorNameInput").value=op?.name||"";$("#operatorDialogTitle").textContent=edit?"تعديل المشغل":"إضافة مشغل جديد";$("#deleteOperator").classList.toggle("hidden",!edit||state.operators.length===1);$("#operatorError").textContent="";$("#operatorDialog").showModal()}
function saveOperator(e){e.preventDefault();const id=$("#operatorEditId").value,name=$("#operatorNameInput").value.trim();if(!name){$("#operatorError").textContent="أدخل اسم المشغل.";return}const duplicate=state.operators.some(operator=>operator.name===name&&operator.id!==id);if(duplicate){$("#operatorError").textContent="يوجد مشغل بهذا الاسم بالفعل.";return}if(id){state.operators=state.operators.map(operator=>operator.id===id?{...operator,name}:operator);showToast("تم تحديث المشغل","تم حفظ اسم المشغل بنجاح.")}else{const newId=`op${Date.now()}`;state.operators.push({id:newId,name});state.activeOperatorId=newId;showToast("تمت إضافة المشغل","كل العمال متاحون الآن في كشفه.")}persist();$("#operatorDialog").close();resetForm();render()}
function askDeleteRecord(id){const r=state.records.find(x=>x.id===id);state.deleteAction=()=>{state.records=state.records.filter(x=>x.id!==id);persist();render();showToast("تم حذف السجل","تم تحديث إجماليات الكشف.")};$("#confirmTitle").textContent="حذف سجل العمل؟";$("#confirmMessage").textContent=`سيتم حذف سجل ${dateInfo(r.date).day} وتحديث المستحقات.`;$("#confirmDialog").showModal()}
function askDeleteOperator(){const op=currentOperator();state.deleteAction=()=>{state.records=state.records.filter(r=>r.operatorId!==op.id);state.operators=state.operators.filter(o=>o.id!==op.id);state.activeOperatorId=state.operators[0].id;persist();$("#operatorDialog").close();resetForm();render();showToast("تم حذف المشغل","تم حذف المشغل وسجلاته من النظام.")};$("#confirmTitle").textContent="حذف المشغل وكل سجلاته؟";$("#confirmMessage").textContent=`سيتم حذف ${op.name} وجميع سجلات أعماله نهائياً.`;$("#confirmDialog").showModal()}
function renderWorkers(){const workers=state.workers.filter(worker=>!worker.archived);$("#globalWorkerCount").textContent=`${number(workers.length)} عمال`;$("#workersBody").innerHTML=workers.map((worker,index)=>{const uses=state.records.filter(record=>record.worker1Id===worker.id||record.worker2Id===worker.id).length;return`<tr><td><strong>${number(index+1)}</strong></td><td><button class="worker-open" data-id="${worker.id}"><span class="person-avatar">${initials(worker.name)}</span><span><strong>${worker.name}</strong><small>عرض الكشف الشهري</small></span><b>‹</b></button></td><td>${number(uses)} سجلات</td><td><span class="role">نشط</span></td><td><div class="row-actions"><button class="icon-btn edit-worker" data-id="${worker.id}" aria-label="تعديل العامل"><svg><use href="#i-edit"/></svg></button><button class="icon-btn delete delete-worker" data-id="${worker.id}" aria-label="حذف العامل"><svg><use href="#i-trash"/></svg></button></div></td></tr>`}).join("");$("#workersEmpty").classList.toggle("hidden",workers.length>0);$("#workersBody").closest("table").classList.toggle("hidden",workers.length===0);document.querySelectorAll(".worker-open").forEach(button=>button.onclick=()=>openWorkerDetail(button.dataset.id));document.querySelectorAll(".edit-worker").forEach(button=>button.onclick=()=>openWorkerDialog(button.dataset.id));document.querySelectorAll(".delete-worker").forEach(button=>button.onclick=()=>askDeleteWorker(button.dataset.id))}
function openWorkerDetail(id){state.activeWorkerId=id;$("#workerMonthFilter").value=el.month.value;$("#workersHome").classList.add("hidden");$("#workerDetail").classList.remove("hidden");location.hash=`worker/${id}`;renderWorkerDetail();window.scrollTo({top:0,behavior:"smooth"})}
function showWorkersHome(){state.activeWorkerId=null;$("#workerDetail").classList.add("hidden");$("#workersHome").classList.remove("hidden");if(document.body.classList.contains("workers-view"))location.hash="workers";renderWorkers()}
function renderWorkerDetail(){if(!state.activeWorkerId)return;const selectedWorker=state.workers.find(worker=>worker.id===state.activeWorkerId);if(!selectedWorker){showWorkersHome();return}const selectedMonth=$("#workerMonthFilter").value,period=payPeriod(selectedMonth),rows=state.records.filter(record=>(record.worker1Id===selectedWorker.id||record.worker2Id===selectedWorker.id)&&record.date>=period.start&&record.date<=period.end).sort((a,b)=>a.date.localeCompare(b.date));const[year,month]=selectedMonth.split("-").map(Number),monthName=new Intl.DateTimeFormat("ar-JO",{month:"long",year:"numeric"}).format(new Date(year,month-1));$("#detailWorkerAvatar").textContent=initials(selectedWorker.name);$("#detailWorkerName").textContent=selectedWorker.name;$("#detailMonthName").textContent=monthName;$("#detailPeriodRange").textContent=period.label;const operatorCount=new Set(rows.map(record=>record.operatorId)).size;$("#detailWorkerSubtitle").textContent=operatorCount?`عمل مع ${number(operatorCount)} مشغلين في هذه الفترة`:"لا توجد أعمال في هذه الفترة";$("#workerRecordsBody").innerHTML=rows.map((record,index)=>{const op=operatorById(record.operatorId),date=dateInfo(record.date),workerMeters=record.meters/(record.worker2Id?2:1),due=workerMeters*WORKER_RATE,position=record.worker1Id===selectedWorker.id?"العامل الأول":"العامل الثاني";return`<tr><td><strong>${number(index+1)}</strong></td><td><strong>${date.day}</strong></td><td>${record.date.split("-").reverse().join("/")}</td><td><div class="person"><span class="person-avatar operator-mini">${initials(op?.name||"—")}</span><span><strong>${op?.name||"مشغل محذوف"}</strong><small>مشغل</small></span></div></td><td><span class="position-badge">${position}</span></td><td>${number(record.meters)} متر</td><td><strong>${number(workerMeters)} متر</strong></td><td class="money">${money(due)}</td></tr>`}).join("");$("#workerRecordsEmpty").classList.toggle("hidden",rows.length>0);$("#workerRecordsBody").closest("table").classList.toggle("hidden",rows.length===0);const totalMeters=rows.reduce((sum,record)=>sum+record.meters/(record.worker2Id?2:1),0),totalDue=totalMeters*WORKER_RATE;$("#detailWorkDays").textContent=`${number(new Set(rows.map(record=>record.date)).size)} أيام`;$("#detailOperatorCount").textContent=`${number(operatorCount)} مشغلين`;$("#detailWorkerMeters").textContent=`${number(totalMeters)} متر`;$("#detailWorkerDue").textContent=money(totalDue);$("#detailTableMeters").textContent=`${number(totalMeters)} متر`;$("#detailTableDue").textContent=money(totalDue);$("#detailRecordsSubtitle").innerHTML=`${number(rows.length)} سجلات · <bdi dir="ltr">${period.label}</bdi>`;document.title=`كشف ${selectedWorker.name} — ${monthName}`}
renderWorkerDetail=function(){
  if(!state.activeWorkerId)return;
  const selectedWorker=state.workers.find(worker=>worker.id===state.activeWorkerId);
  if(!selectedWorker){showWorkersHome();return}
  const selectedMonth=$("#workerMonthFilter").value,period=payPeriod(selectedMonth);
  const rows=state.records.filter(record=>(record.worker1Id===selectedWorker.id||record.worker2Id===selectedWorker.id)&&record.date>=period.start&&record.date<=period.end).sort((a,b)=>a.date.localeCompare(b.date));
  const[year,month]=selectedMonth.split("-").map(Number),monthName=new Intl.DateTimeFormat("ar-JO",{month:"long",year:"numeric"}).format(new Date(year,month-1));
  $("#detailWorkerAvatar").textContent=initials(selectedWorker.name);$("#detailWorkerName").textContent=selectedWorker.name;$("#detailMonthName").textContent=monthName;$("#detailPeriodRange").textContent=period.label;
  const operatorCount=new Set(rows.map(record=>record.operatorId)).size;
  $("#detailWorkerSubtitle").textContent=operatorCount?`عمل مع ${number(operatorCount)} مشغلين في هذه الفترة`:"لا توجد أعمال في هذه الفترة";
  $("#workerRecordsBody").innerHTML=rows.map((record,index)=>{const op=operatorById(record.operatorId),date=dateInfo(record.date),workerMeters=record.meters/(record.worker2Id?2:1),due=workerMeters*WORKER_RATE,position=record.worker1Id===selectedWorker.id?"العامل الأول":"العامل الثاني";return`<tr><td><strong>${number(index+1)}</strong></td><td><strong>${date.day}</strong></td><td>${record.date.split("-").reverse().join("/")}</td><td><div class="person"><span class="person-avatar operator-mini">${initials(op?.name||"—")}</span><span><strong>${op?.name||"مشغل محذوف"}</strong><small>مشغل</small></span></div></td><td><span class="position-badge">${position}</span></td><td>${additionsCell(record.additions)}</td><td>${number(record.meters)} متر</td><td><strong>${number(workerMeters)} متر</strong></td><td class="money">${money(due)}</td></tr>`}).join("");
  $("#workerRecordsEmpty").classList.toggle("hidden",rows.length>0);$("#workerRecordsBody").closest("table").classList.toggle("hidden",rows.length===0);
  const totalMeters=rows.reduce((sum,record)=>sum+record.meters/(record.worker2Id?2:1),0),additionsTotal=rows.reduce((sum,record)=>sum+additionsValue(record.additions),0),totalDue=totalMeters*WORKER_RATE;
  $("#detailWorkDays").textContent=`${number(new Set(rows.map(record=>record.date)).size)} أيام`;$("#detailOperatorCount").textContent=`${number(operatorCount)} مشغلين`;$("#detailWorkerMeters").textContent=`${number(totalMeters)} متر`;$("#detailWorkerDue").textContent=money(totalDue);$("#detailAdditionsTotal").textContent=money(additionsTotal);$("#detailTableMeters").textContent=`${number(totalMeters)} متر`;$("#detailTableDue").textContent=money(totalDue);$("#detailRecordsSubtitle").innerHTML=`${number(rows.length)} سجلات · <bdi dir="ltr">${period.label}</bdi>`;document.title=`كشف ${selectedWorker.name} — ${monthName}`;
};
function openWorkerDialog(id=""){const existing=state.workers.find(worker=>worker.id===id);$("#workerEditId").value=existing?.id||"";$("#workerNameInput").value=existing?.name||"";$("#workerDialogTitle").textContent=existing?"تعديل العامل":"إضافة عامل";$("#workerError").textContent="";$("#workerDialog").showModal()}
function saveWorker(event){event.preventDefault();const id=$("#workerEditId").value,name=$("#workerNameInput").value.trim();if(!name){$("#workerError").textContent="أدخل اسم العامل.";return}const duplicate=state.workers.some(worker=>worker.name===name&&worker.id!==id&&!worker.archived);if(duplicate){$("#workerError").textContent="يوجد عامل بهذا الاسم بالفعل.";return}if(id){state.workers=state.workers.map(worker=>worker.id===id?{...worker,name}:worker);showToast("تم تحديث العامل","ظهر الاسم الجديد في جميع السجلات.")}else{state.workers.push({id:`w${Date.now()}`,name});showToast("تمت إضافة العامل","أصبح العامل متاحاً لجميع المشغلين.")}persist();$("#workerDialog").close();render()}
function askDeleteWorker(id){const selectedWorker=state.workers.find(worker=>worker.id===id),used=state.records.some(record=>record.worker1Id===id||record.worker2Id===id);state.deleteAction=()=>{if(used)state.workers=state.workers.map(worker=>worker.id===id?{...worker,archived:true}:worker);else state.workers=state.workers.filter(worker=>worker.id!==id);persist();resetForm();render();showToast("تم حذف العامل",used?"تم إخفاؤه من القوائم مع حفظ سجلاته السابقة.":"تم حذف العامل من القائمة.")};$("#confirmTitle").textContent="حذف العامل؟";$("#confirmMessage").textContent=used?`سيختفي ${selectedWorker.name} من قوائم الاختيار، وستبقى سجلاته السابقة محفوظة.`:`سيتم حذف ${selectedWorker.name} من قائمة العمال.`;$("#confirmDialog").showModal()}
function switchPage(page){const workersPage=page==="workers";$("#sheetPage").classList.toggle("hidden",workersPage);$("#workersPage").classList.toggle("hidden",!workersPage);document.body.classList.toggle("workers-view",workersPage);document.querySelectorAll(".main-tabs button").forEach(button=>button.classList.toggle("active",button.dataset.page===page));location.hash=workersPage?"workers":"sheet";if(workersPage){showWorkersHome();document.title="العمال — سجل الإنتاج"}else renderHeader();window.scrollTo({top:0,behavior:"smooth"})}
const editRecordWithoutAdditions=editRecord;
editRecord=function(id){editRecordWithoutAdditions(id);const record=state.records.find(item=>item.id===id);document.querySelectorAll('input[name="additions"]').forEach(input=>input.checked=(record?.additions||[]).includes(input.value));updateAdditionsLabel();updatePreview()};
function submitRecordWithAdditions(event){event.preventDefault();if(!validateRecord())return;const item={id:state.editingRecordId||`r${Date.now()}`,date:el.date.value,operatorId:state.activeOperatorId,worker1Id:el.worker1.value,worker2Id:el.worker2.value,meters:Number(el.meters.value),additions:selectedAdditions()};if(state.editingRecordId){state.records=state.records.map(record=>record.id===item.id?item:record);showToast("تم تعديل السجل","تم تحديث المستحقات والإضافات.")}else{state.records.push(item);showToast("تمت إضافة السجل","تم حفظ العمل والإضافات في الكشف.")}persist();resetForm();render()}
window.addEventListener("load",()=>{el.form.onsubmit=submitRecordWithAdditions;$("#additionsToggle").onclick=()=>$("#additionsMenu").classList.toggle("hidden");document.querySelectorAll('input[name="additions"]').forEach(input=>input.onchange=()=>{updateAdditionsLabel();updatePreview()});document.addEventListener("click",event=>{if(!$("#additionsSelect").contains(event.target))$("#additionsMenu").classList.add("hidden")})});
el.form.addEventListener("reset",()=>$("#additionsMenu").classList.add("hidden"));
let toastTimer;function showToast(title,message){clearTimeout(toastTimer);$("#toastTitle").textContent=title;$("#toastMessage").textContent=message;$("#toast").classList.add("show");toastTimer=setTimeout(()=>$("#toast").classList.remove("show"),3000)}

const initialHash=location.hash;fillOperatorSelect();resetForm();render();if(initialHash.startsWith("#worker/")){switchPage("workers");openWorkerDetail(initialHash.replace("#worker/",""))}else switchPage(initialHash==="#workers"?"workers":"sheet");
el.operator.onchange=()=>{state.activeOperatorId=el.operator.value;persist();resetForm();render()};el.month.onchange=()=>{resetForm();render()};el.worker1.onchange=()=>{syncWorkerChoices();updatePreview()};el.worker2.onchange=()=>{syncWorkerChoices();updatePreview()};el.meters.oninput=updatePreview;el.form.onsubmit=submitRecord;el.form.oninput=e=>e.target.closest(".field")?.classList.remove("invalid");$("#cancelEdit").onclick=resetForm;$("#addOperator").onclick=()=>openOperatorDialog(false);$("#editOperator").onclick=()=>openOperatorDialog(true);$("#operatorForm").onsubmit=saveOperator;$("#deleteOperator").onclick=askDeleteOperator;$("#addWorker").onclick=()=>openWorkerDialog();$("#workerForm").onsubmit=saveWorker;$("#backToWorkers").onclick=showWorkersHome;$("#workerMonthFilter").onchange=renderWorkerDetail;document.querySelectorAll(".main-tabs button").forEach(button=>button.onclick=()=>switchPage(button.dataset.page));$("#confirmDelete").onclick=()=>{const action=state.deleteAction;state.deleteAction=null;$("#confirmDialog").close();action?.()};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).close());$("#printBtn").onclick=()=>window.print();
